x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  init:
    restart: "no"
    build:
      context: ./init
      dockerfile: Dockerfile
    image: init:polygon-zkevm
    user: 1000:1000
    pull_policy: never
    environment:
      - SNAPSHOT=${SNAPSHOT:-}
    volumes:
      - zkevm-erigon-data:/tmp/cdk-erigon
      - /etc/localtime:/etc/localtime:ro

  cdk-erigon:
    image: ${NETWORK}-cdk-erigon:local
    build:
      context: ${DOCKER_CONTEXT}
      dockerfile: ${ERIGON_DOCKERFILE}
      args:
        - DOCKER_TAG=${DOCKER_TAG}
        - DOCKER_REPO=${DOCKER_REPO}
    restart: "unless-stopped"
    pull_policy: never
    user: 1000:1000
    volumes:
      - zkevm-erigon-data:/home/erigon/.local/share/erigon
      - ./config:/home/erigon/.local/share/erigon-config
    mem_swappiness: 0
    depends_on:
      init:
        condition: service_completed_successfully
    entrypoint:
      - cdk-erigon
      - --config
      - /home/erigon/.local/share/erigon-config/${NETWORK}.yaml
      - --zkevm.l1-rpc-url
      - ${L1_RPC}
      - --zkevm.rpc-ratelimit
      - ${L1_RPC_RATELIMIT}
      - --maxpeers
      - "32"
      - --downloader.disable.ipv6
      - --http
      - --http.api
      - eth,net,trace,web3,erigon,zkevm
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${RPC_PORT}
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.api
      - eth,net,trace,web3,erigon,zkevm
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${WS_PORT}
      - --metrics
      - --metrics.addr
      - 0.0.0.0
    command: ${ERIGON_EXTRAS}
    labels:
      - metrics.scrape=true
      - metrics.port=6060
      - metrics.path=/debug/metrics/prometheus
      - metrics.network=polygon-zkevm-${NETWORK}
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST}.service=${RPC_HOST}
      - traefik.http.routers.${RPC_HOST}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST}.rule=Host(`${RPC_HOST}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST}lb.service=${RPC_HOST}
      - traefik.http.routers.${RPC_HOST}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST}lb.rule=Host(`${RPC_LB}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST}.loadbalancer.server.port=${RPC_PORT}
      - traefik.http.routers.${WS_HOST}.service=${WS_HOST}
      - traefik.http.routers.${WS_HOST}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST}.rule=Host(`${WS_HOST}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST}lb.service=${WS_HOST}
      - traefik.http.routers.${WS_HOST}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST}lb.rule=Host(`${WS_LB}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST}.loadbalancer.server.port=${WS_PORT}
    <<: *logging

volumes:
  zkevm-erigon-data:
